# Generated by Django 3.1.7 on 2021-03-01 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('text', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('tools', models.CharField(max_length=300)),
            ],
        ),
    ]
